(function(){
	angular.module('Life')
		.factory('GameBoardFactory', GameBoardFactory);

		function GameBoardFactory () {
			return {
				setBoardMirrorPerpendicular: function(array){
					array[618].isAlive = true;
					array[619].isAlive = true;
					array[620].isAlive = true;
					array[659].isAlive = true;
					array[699].isAlive = true;
					array[739].isAlive = true;
					array[859].isAlive = true;
					array[899].isAlive = true;
					array[939].isAlive = true;
					array[978].isAlive = true;
					array[979].isAlive = true;
					array[980].isAlive = true;
				},
				setBoardPlusSquareDiamond: function(array){
					array[414].isAlive = true;
					array[415].isAlive = true;
					array[416].isAlive = true;
					array[417].isAlive = true;
					array[418].isAlive = true;
					array[419].isAlive = true;
					array[420].isAlive = true;
					array[421].isAlive = true;
					array[422].isAlive = true;
					array[423].isAlive = true;
					array[424].isAlive = true;
					array[425].isAlive = true;
					array[426].isAlive = true;
					array[466].isAlive = true;
					array[506].isAlive = true;
					array[546].isAlive = true;
					array[586].isAlive = true;
					array[626].isAlive = true;
					array[666].isAlive = true;
					array[706].isAlive = true;
					array[746].isAlive = true;
					array[786].isAlive = true;
					array[826].isAlive = true;
					array[866].isAlive = true;
					array[906].isAlive = true;
					array[905].isAlive = true;
					array[904].isAlive = true;
					array[903].isAlive = true;
					array[902].isAlive = true;
					array[901].isAlive = true;
					array[900].isAlive = true;
					array[899].isAlive = true;
					array[898].isAlive = true;
					array[897].isAlive = true;
					array[896].isAlive = true;
					array[895].isAlive = true;
					array[894].isAlive = true;
					array[854].isAlive = true;
					array[814].isAlive = true;
					array[774].isAlive = true;
					array[734].isAlive = true;
					array[694].isAlive = true;
					array[654].isAlive = true;
					array[614].isAlive = true;
					array[574].isAlive = true;
					array[534].isAlive = true;
					array[494].isAlive = true;
					array[454].isAlive = true;

					//inner plus
					array[539].isAlive = true;
					array[540].isAlive = true;
					array[541].isAlive = true;
					array[581].isAlive = true;
					array[621].isAlive = true;
					array[622].isAlive = true;
					array[623].isAlive = true;
					array[663].isAlive = true;
					array[703].isAlive = true;
					array[702].isAlive = true;
					array[701].isAlive = true;
					array[741].isAlive = true;
					array[781].isAlive = true;
					array[780].isAlive = true;
					array[779].isAlive = true;
					array[739].isAlive = true;
					array[699].isAlive = true;
					array[698].isAlive = true;
					array[697].isAlive = true;
					array[657].isAlive = true;
					array[617].isAlive = true;
					array[618].isAlive = true;
					array[619].isAlive = true;
					array[579].isAlive = true;

					//diamond
					array[20].isAlive = true;
					array[61].isAlive = true;
					array[102].isAlive = true;
					array[143].isAlive = true;
					array[184].isAlive = true;
					array[225].isAlive = true;
					array[266].isAlive = true;
					array[307].isAlive = true;
					array[348].isAlive = true;
					array[389].isAlive = true;
					array[430].isAlive = true;
					array[471].isAlive = true;
					array[512].isAlive = true;
					array[553].isAlive = true;
					array[594].isAlive = true;
					array[635].isAlive = true;
					array[676].isAlive = true;
					array[715].isAlive = true;
					array[754].isAlive = true;
					array[793].isAlive = true;
					array[832].isAlive = true;
					array[871].isAlive = true;
					array[910].isAlive = true;
					array[949].isAlive = true;
					array[988].isAlive = true;
					array[1027].isAlive = true;
					array[1066].isAlive = true;
					array[1105].isAlive = true;
					array[1144].isAlive = true;
					array[1183].isAlive = true;
					array[1222].isAlive = true;
					array[1261].isAlive = true;
					array[1300].isAlive = true;
					array[1259].isAlive = true;
					array[1218].isAlive = true;
					array[1177].isAlive = true;
					array[1136].isAlive = true;
					array[1095].isAlive = true;
					array[1054].isAlive = true;
					array[1013].isAlive = true;
					array[972].isAlive = true;
					array[931].isAlive = true;
					array[890].isAlive = true;
					array[849].isAlive = true;
					array[808].isAlive = true;
					array[767].isAlive = true;
					array[726].isAlive = true;
					array[685].isAlive = true;
					array[644].isAlive = true;
					array[605].isAlive = true;
					array[566].isAlive = true;
					array[527].isAlive = true;
					array[488].isAlive = true;
					array[449].isAlive = true;
					array[410].isAlive = true;
					array[371].isAlive = true;
					array[332].isAlive = true;
					array[293].isAlive = true;
					array[254].isAlive = true;
					array[215].isAlive = true;
					array[176].isAlive = true;
					array[137].isAlive = true;
					array[98].isAlive = true;
					array[59].isAlive = true;
				},
				setBoardPlusSquare: function(array){
					array[414].isAlive = true;
					array[415].isAlive = true;
					array[416].isAlive = true;
					array[417].isAlive = true;
					array[418].isAlive = true;
					array[419].isAlive = true;
					array[420].isAlive = true;
					array[421].isAlive = true;
					array[422].isAlive = true;
					array[423].isAlive = true;
					array[424].isAlive = true;
					array[425].isAlive = true;
					array[426].isAlive = true;
					array[466].isAlive = true;
					array[506].isAlive = true;
					array[546].isAlive = true;
					array[586].isAlive = true;
					array[626].isAlive = true;
					array[666].isAlive = true;
					array[706].isAlive = true;
					array[746].isAlive = true;
					array[786].isAlive = true;
					array[826].isAlive = true;
					array[866].isAlive = true;
					array[906].isAlive = true;
					array[905].isAlive = true;
					array[904].isAlive = true;
					array[903].isAlive = true;
					array[902].isAlive = true;
					array[901].isAlive = true;
					array[900].isAlive = true;
					array[899].isAlive = true;
					array[898].isAlive = true;
					array[897].isAlive = true;
					array[896].isAlive = true;
					array[895].isAlive = true;
					array[894].isAlive = true;
					array[854].isAlive = true;
					array[814].isAlive = true;
					array[774].isAlive = true;
					array[734].isAlive = true;
					array[694].isAlive = true;
					array[654].isAlive = true;
					array[614].isAlive = true;
					array[574].isAlive = true;
					array[534].isAlive = true;
					array[494].isAlive = true;
					array[454].isAlive = true;

					//inner plus
					array[539].isAlive = true;
					array[540].isAlive = true;
					array[541].isAlive = true;
					array[581].isAlive = true;
					array[621].isAlive = true;
					array[622].isAlive = true;
					array[623].isAlive = true;
					array[663].isAlive = true;
					array[703].isAlive = true;
					array[702].isAlive = true;
					array[701].isAlive = true;
					array[741].isAlive = true;
					array[781].isAlive = true;
					array[780].isAlive = true;
					array[779].isAlive = true;
					array[739].isAlive = true;
					array[699].isAlive = true;
					array[698].isAlive = true;
					array[697].isAlive = true;
					array[657].isAlive = true;
					array[617].isAlive = true;
					array[618].isAlive = true;
					array[619].isAlive = true;
					array[579].isAlive = true;
				},
				setBoardPerpendicular: function(array){
					array[659].isAlive = true;
					array[699].isAlive = true;
					array[739].isAlive = true;
					array[779].isAlive = true;
					array[778].isAlive = true;
					array[780].isAlive = true;	
				},
				setBoardBeacon: function(array) {
					array[416].isAlive = true;
					array[417].isAlive = true;
					array[456].isAlive = true;
					array[499].isAlive = true;
					array[539].isAlive = true;
					array[538].isAlive = true;	
				},
				setBoardToad: function (array){
					array[70].isAlive = true;
					array[71].isAlive = true;
					array[72].isAlive = true;
					array[89].isAlive = true;
					array[90].isAlive = true;
					array[91].isAlive = true;
				},
				setBoardGliderGun: function (array){
					array[201].isAlive = true;
					array[241].isAlive = true;
					array[202].isAlive = true;
					array[242].isAlive = true;

					array[133].isAlive = true;
					array[134].isAlive = true;
					array[176].isAlive = true;
					array[217].isAlive = true;
					array[255].isAlive = true;
					array[257].isAlive = true;
					array[258].isAlive = true;
					array[297].isAlive = true;
					array[172].isAlive = true;
					array[211].isAlive = true;
					array[251].isAlive = true;
					array[291].isAlive = true;
					array[332].isAlive = true;
					array[373].isAlive = true;
					array[374].isAlive = true;
					array[336].isAlive = true;

					array[221].isAlive = true;
					array[222].isAlive = true;
					array[181].isAlive = true;
					array[182].isAlive = true;
					array[141].isAlive = true;
					array[142].isAlive = true;
					array[103].isAlive = true;
					array[105].isAlive = true;
					array[65].isAlive = true;
					array[263].isAlive = true;
					array[265].isAlive = true;
					array[305].isAlive = true;

					array[155].isAlive = true;
					array[156].isAlive = true;
					array[195].isAlive = true;
					array[196].isAlive = true;
				},
				setBoardPulsar: function (array){
					array[291].isAlive = true;
					array[292].isAlive = true;
					array[293].isAlive = true;
					array[374].isAlive = true;
					array[414].isAlive = true;
					array[454].isAlive = true;
					array[493].isAlive = true;
					array[492].isAlive = true;
					array[491].isAlive = true;
					array[369].isAlive = true;
					array[409].isAlive = true;
					array[449].isAlive = true;
					array[298].isAlive = true;
					array[299].isAlive = true;
					array[297].isAlive = true;
					array[381].isAlive = true;
					array[421].isAlive = true;
					array[461].isAlive = true;
					array[497].isAlive = true;
					array[498].isAlive = true;
					array[499].isAlive = true;
					array[376].isAlive = true;
					array[416].isAlive = true;
					array[456].isAlive = true;
					array[571].isAlive = true;
					array[572].isAlive = true;
					array[573].isAlive = true;
					array[614].isAlive = true;
					array[654].isAlive = true;
					array[694].isAlive = true;
					array[773].isAlive = true;
					array[772].isAlive = true;
					array[771].isAlive = true;
					array[609].isAlive = true;
					array[649].isAlive = true;	
					array[689].isAlive = true;
					array[577].isAlive = true;
					array[578].isAlive = true;
					array[579].isAlive = true;
					array[621].isAlive = true;
					array[661].isAlive = true;
					array[701].isAlive = true;
					array[777].isAlive = true;
					array[779].isAlive = true;
					array[778].isAlive = true;
					array[616].isAlive = true;
					array[656].isAlive = true;
					array[696].isAlive = true;
				},
				setBoardCross: function (array){
					array[95].isAlive = true;
					array[135].isAlive = true;
					array[175].isAlive = true;
					array[215].isAlive = true;
					array[255].isAlive = true;

					array[415].isAlive = true;
					array[455].isAlive = true;
					array[495].isAlive = true;
					array[535].isAlive = true;
					array[575].isAlive = true;

					
					array[332].isAlive = true;
					array[331].isAlive = true;
					array[330].isAlive = true;
					array[329].isAlive = true;
					array[328].isAlive = true;
					array[327].isAlive = true;
					array[326].isAlive = true;
					array[325].isAlive = true;
					array[324].isAlive = true;
					array[323].isAlive = true;

					array[338].isAlive = true;
					array[339].isAlive = true;
					array[340].isAlive = true;
					array[341].isAlive = true;
					array[342].isAlive = true;
					array[343].isAlive = true;
					array[344].isAlive = true;
					array[345].isAlive = true;
					array[346].isAlive = true;
					array[347].isAlive = true;

					array[725].isAlive = true;
					array[727].isAlive = true;
					array[724].isAlive = true;
					array[723].isAlive = true;
					array[223].isAlive = true;
					array[224].isAlive = true;
					array[225].isAlive = true;
					array[227].isAlive = true;

					array[121].isAlive = true;
					array[122].isAlive = true;
					array[123].isAlive = true;
					array[201].isAlive = true;
					array[202].isAlive = true;
					array[203].isAlive = true;
				}, 
				setBoardCross: function(array){
					array[460].isAlive = true;
					array[180].isAlive = true;
					array[220].isAlive = true;
					array[260].isAlive = true;
					array[300].isAlive = true;
					array[340].isAlive = true;
					array[380].isAlive = true;
					array[420].isAlive = true;

					array[900].isAlive = true;
					array[620].isAlive = true;
					array[660].isAlive = true;
					array[700].isAlive = true;
					array[740].isAlive = true;
					array[780].isAlive = true;
					array[820].isAlive = true;
					array[860].isAlive = true;

					array[539].isAlive = true;
					array[538].isAlive = true;
					array[537].isAlive = true;
					array[536].isAlive = true;
					array[535].isAlive = true;
					array[534].isAlive = true;
					array[533].isAlive = true;
					array[532].isAlive = true;

					array[541].isAlive = true;
					array[542].isAlive = true;
					array[543].isAlive = true;
					array[544].isAlive = true;
					array[545].isAlive = true;
					array[546].isAlive = true;
					array[547].isAlive = true;
					array[548].isAlive = true;
				}

			}
		}
})();